# Generated by Django 4.2.10 on 2025-12-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.AddField(
            model_name="student",
            name="stid",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
